# Generated by Django 4.1.3 on 2022-12-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_call_plans_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='sms',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
